# https://docs.readthedocs.com/platform/stable/intro/mkdocs.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3"
  jobs:
    pre_build:
      - make pre-build

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: requirements.txt
